site_name: Amba Analysis Worker Aggregator
site_description: 'documentation for amba-analysis-worker-aggregator'
site_author: 'Lukas Jesche'
docs_dir: docs/
repo_name: 'ambalytics/amba-analysis-worker-aggregator'
repo_url: 'https://github.com/ambalytics/amba-analysis-worker-aggregator'
nav:
    - Home: index.md
    - Code Reference:
        main: main_ref.md
        daos:
          author: daos/author_ref.md
          database: daos/database_ref.md
          field_of_study: daos/field_of_study_ref.md
          publication: daos/publication_ref.md
          stats: daos/stats_ref.md
        models:
          schema: models/schema_red.md
        routers:
          author: routers/author_ref.md
          field_of_study: routers/field_of_study_ref.md
          publication: routers/publication_ref.md
          stats: routers/stats_ref.md
        update_consumer: update_consumer_ref.md

theme:
  name: material
  palette:
    scheme: preference
    primary: teal
    accent: purple

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - from unittest.mock import MagicMock as mock
            - sys.path.append("app")
            - sys.modules["event_stream"] = mock()
            - sys.modules["event_stream.models"] = mock()
            - sys.modules["event_stream.models.model"] = mock()
            - sys.modules["sqlalchemy"] = mock()
            - sys.modules["sqlalchemy.orm"] = mock()
            - sys.modules["sqlalchemy.engine"] = mock()
            - sys.modules["sqlalchemy.ext.declarative"] = mock()
